config/routes.rb
Rails.application.routes.draw do
  
  

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'trips/index'

	
	
  resources :trips do
  	resources :microposts
  end
  
	
  
  resources :guest
  
	resources :commitment
	
  	root 'static_pages#home'
  	get 'login'  => 'sessions#new'
	post 'login'  => 'sessions#create'
	delete 'logout'  => 'sessions#destroy'
	
	post '/trips/:id/users/new' => 'trips#add_user', as: :add_user
	delete 'trips/:id/users/:user_id' => 'trips#remove_user', as: :remove_user
	post '/users/:id/trips/new' => 'users#add_trip', as: :add_trip
	delete '/users/:id/trips/:trip_id' => 'users#remove_trip', as: :remove_trip
	
	resources :filters
	resources :users
	resources :password_resets, only:[:new, :create, :edit, :update]
	
 
	
  

end

app/models/trip.rb
class Trip < ActiveRecord::Base
	has_many :users_trips, dependent: :destroy
	has_many :users, through: :users_trips
	has_many :taggings
	has_many :tags, through: :taggings
	has_many :microposts, dependent: :destroy
	
	def all_tags=(names)
	  self.tags = names.split(",").map do |name|
		  Tag.where(name: name.downcase.strip).first_or_create!
	  end
	end
 
	def all_tags
	  self.tags.map(&:name).join(", ")
	end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :logged_in_user, only: [:create, :edit, :update, :destroy, :add_user]
  before_action :admin_user,     only: :destroy

  def index
  		@trips=Trip.all
  	end
  
  	def new
  		@trip=Trip.new
  	end
  
	def create
  		@trip = Trip.new(trip_params)	
  		@trip.lead=current_user.id
  		@trip.dest.split(",").each do |t|
  			@tags = @trip.tags.build(name: t.downcase.strip)
 		end 	
  		if @trip.save
      		flash[:success] = "Bom Voyage"
 			redirect_to @trip
  		else
    		render 'new'
  		end	
	end
	
	def show
		@trip = Trip.find(params[:id])
		@users = User.all
		@microposts = @trip.microposts
	end
	
	
	def edit
		@trip = Trip.find(params[:id])
	end
	
	def update
  		@trip = Trip.find(params[:id])
  		if @trip.update(trip_params)
  			flash[:success] = "Trip Profile updated"
    		redirect_to @trip
  		else
    		render 'edit'
  		end
  
	end
	
	def destroy
		Trip.find(params[:id]).destroy
		flash[:success]="Trip deleted"
		redirect_to trips_path
	end
	

	def add_user
  	 	trip = Trip.find(params[:id])
  	 	user = current_user
  	#OJO:or User.find(params[:user_id]) / wouldnt need @user=Users.all
  	 	trip.users << user
  	 	redirect_to trip_path(trip)
	end
	
	def remove_user
  	 	trip = Trip.find(params[:id])
  	 	user = User.find(params[:user_id])
  	 	trip.users.delete(user)
  	 	redirect_to trip_path(trip)
	end

	def logged_in_user
  		unless logged_in?
  			flash[:danger]= "Please log in."
  			redirect_to login_path
  		end
  	end


	private
  	def trip_params
    	params.require(:trip).permit(:name, :dest, :desc, :month, :image, :lead, :all_tags)
  	end	
  	
  	
  	
  	def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
	
	

	
  	

end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_edform.html.erb
<%= form_for @trip do |t| %>
 
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@trip.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @trip.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
 <p>
    <%= t.label :name %><br>
    <%= t.text_field :name %>
  </p>
  
  <p>
    <%= t.label :dest %><br>
    <%= t.text_field :dest %>
  </p>
  
  <p>
    <%= t.label :month %><br>
    <%= t.text_field :month %>
  </p>
  
  <p>
    <%= t.label :desc %><br>
    <%= t.text_field :desc %>
  </p>
  
   <p>
    <%= t.label :image %><br>
    <%= t.text_field :image %>
  </p>
  
   <p>
  	<%= t.label "Tags" %><br>
  	<%= t.text_field :all_tags, placeholder: "Tags separated with comma" %>
  </p>
  
  <p>
    <%= t.submit "Update!!", class: "btn-srch" %>
  </p>
 
<% end %>

app/views/trips/_form.html.erb
<%= form_for @trip do |t| %>
 
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@trip.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @trip.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
 <p>
    <%= t.label :name %><br>
    <%= t.text_field :name, class: 'form-control' %>
  </p>
  
  <p>
    <%= t.label "Destination" %><br>
    <%= t.text_field :dest, class: 'form-control' %>
  </p>
  
  <p>
    <%= t.label "Date" %><br>
    <%= t.text_field :month, class: 'form-control' %>
  </p>
  
  <p>
    <%= t.label "Description" %><br>
    <%= t.text_field :desc, class: 'form-control' %>
  </p>
  
   <p>
    <%= t.label "Image(html)" %><br>
    <%= t.text_field :image, class: 'form-control' %>
  </p>
  
  <p>
  	<%= t.label "Tags" %><br>
  	<%= t.text_field :all_tags, placeholder: "Tags separated with comma" %>
  </p>
  
  <p>
    <%= t.submit "Set Sail!!", class: "btn-srch" %>
  </p>
 
 
 
<% end %>

app/views/trips/edit.html.erb
<% provide(:title, "edit trips") %>

<h1>Update your profile</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
	
	<%= render 'edform' %>
	
	</div>
 
<%= link_to 'Back', root_path %>

</div>

app/views/trips/index.html.erb
<div class="hero">
  <div class="container">
    <h1>Sharing Adventures</h1>
    <p>Create a trip.  Bring your friends along.  Or tag along.</p>
    <p>Where are you going?</p>
<%= form_tag filters_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", class: "btn-srch" 	%>
  </p>
<% end %>
  </div>
  
</div>

  <div class="container">
  <h2>Browse available trips.</h2>
    <% @trips.each do |trip| %>
    <div class="trip">
      	<%= image_tag trip.image %>
      	<h4><%= trip.name %></h4>
      	<p><%= trip.dest %></p>
      	<p><%= trip.month %></p>
		<p><%= trip.desc %></p>
      	<%= link_to "Details", trip_path(trip) %>
    </div>
    
    <% end %>
  </div>
  
</div>

app/views/trips/new.html.erb
<h1>Start a new Adventure!!</h1>

<div class="row">
<div class="col-md-3 col-md-offset-3">
<%= render 'form' %>

</div>
<h4>Trip themes:</h4>
<br>
<%= check_box_tag(:fixed) %>
<%= label_tag(:fixed, "Set in stone") %>
<%= check_box_tag(:flexibile) %>
<%= label_tag(:flexible, "Day by Day") %>

<br></br>
<%= check_box_tag(:outdoor) %>
<%= label_tag(:outdoor, "Outdoor") %>
<%= check_box_tag(:sight_seeing) %>
<%= label_tag(:sight_seeing, "Sight Seeing") %>

<br></br>
<%= check_box_tag(:x_games) %>
<%= label_tag(:x_games, "Extreme Activities") %>
<%= check_box_tag(:roadtrip) %>
<%= label_tag(:roadtrip, "Roadtrip") %>
<br></br>
<%= check_box_tag(:foodie) %>
<%= label_tag(:foodie, "Foodies") %>
<%= check_box_tag(:clubbing) %>
<%= label_tag(:clubbing, "Clubbing") %>
<br></br>
<%= check_box_tag(:luxury) %>
<%= label_tag(:luxury, "Luxury") %>
<%= check_box_tag(:luxury) %>
<%= label_tag(:bohemian, "Bohemian") %>
<%= check_box_tag(:camping) %>
<%= label_tag(:camping, "Camping") %>
<br></br>
<%= check_box_tag(:non_stop) %>
<%= label_tag(:non_stop, "Non-Stop") %>
<%= check_box_tag(:chill) %>
<%= label_tag(:chill, "Chill") %>
<br></br>
<%= check_box_tag(:all_things) %>
<%= label_tag(:all_things, "A litte bit of everything") %>
</div>
   

app/views/trips/show.html.erb
<div class="center">
	
	<div class="main">
	
	  <div class="container">
	  	<h2>Trip Profile Page</h2>  
	  	<br></br>	
		<div class="main trip-show">
		  	
		  <!-- Display the trip's info here -->    
			<%= image_tag @trip.image %>
			<h2><%= @trip.name %></h2> 
			<p><%= @trip.dest %></p>
			<p><%= @trip.month %></p>
			<p><%= @trip.desc %></p>
			<p><%= @trip.all_tags %></p>
			<% if logged_in? && current_user.admin?  %>
			<p>
				<%= link_to 'Edit', edit_trip_path(@trip) %>
				|
		
				<%= link_to 'Delete', @trip, method: :delete, data: { confirm: "You sure?"} %>
			</p>
			<% end%>
			
		<div id="map-container">
	  		<div id="map-canvas"></div>
		</div>
				
		</div>
			
		<div class="col-md-6">
				<% if @trip.microposts.any? %>
				<h3>Activity (<%= @trip.microposts.count %>)</h3>
				<ol class="microposts">
					<%= render @microposts %>
				</ol>
				<% end %>
		
				<h4>Add a comment:</h4>
				<%= form_for([@trip, @trip.microposts.build]) do |f| %>
				  <p>
					<%= f.text_area :content %>
				  </p>
				  <p>
					<%= f.submit "Post", class: "btn btn-primary"%>
				  </p>
				<% end %>
		</div>
		
		<div class="col-rt-6">
				<h3>Leader: </h3>
				<p><%= @users.find(@trip.lead).name %></p>
				<h3>Voyagers:</h3>
				<% @trip.users.each do |role| %>
				<p><%= link_to "#{role.name}", user_path(role) %></p>
				<% if logged_in? && current_user.admin?  %>
					<p><%= button_to "Remove", remove_user_path(@trip, role), :method => :delete %></p>
				<% end %>
				<% end %>
				
				<br>	
			<h4>Would you like to join us?</h4>
			<%= button_to "Join", add_user_path(@trip), :method => :new %>
			
		</div>	
		
	 </div>	
	 
	
     	
	</div>
	
		
</div> 