config/routes.rb
Rails.application.routes.draw do
  
  

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'trips/index'

	
	
  resources :trips do
  	resources :microposts
  end
  
	
  
  resources :guest
  
	resources :commitment
	
  	root 'static_pages#home'
  	get 'login'  => 'sessions#new'
	post 'login'  => 'sessions#create'
	delete 'logout'  => 'sessions#destroy'
	
	post '/trips/:id/users/new' => 'trips#add_user', as: :add_user
	delete 'trips/:id/users/:user_id' => 'trips#remove_user', as: :remove_user
	post '/users/:id/trips/new' => 'users#add_trip', as: :add_trip
	delete '/users/:id/trips/:trip_id' => 'users#remove_trip', as: :remove_trip
	
	resources :filters
	resources :users
	resources :password_resets, only:[:new, :create, :edit, :update]
	
 
	
  

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

	def create
		@user = User.find_by(email: params[:password_reset][:email].downcase)
	# User find by accesses model based on params passed in form..
	#..which generated create
		if @user
			@user.create_reset_digest
			@user.send_password_reset_email
			flash[:info] = "email sent with password reset instructions"
			redirect_to root_url
		else
			flash.now[:danger] = "Email address not found"
			render 'new'
		end
	end

  def edit
  end
  
  
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<h1>Reset Password</h1>
 <br></br> 

<%= form_for @user do |f| %>
 
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>
  
 <p>
    <%= f.label :passsword_confirmation%><br>
    <%= f.password_field :password_confirmation %>
  </p>
  
  <p>
    <%= f.submit "Create my account", class: "btn btn-primary" %>
  </p>
 
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot Password</h1>
 <br></br> 

<div class="row">
  <div class="col-md-6 col-md-offset-3">

<%= form_for(:password_reset, url: password_resets_path) do |f| %>
  
 <p>
    <%= f.label :email %><br>
    <%= f.email_field :email, class: 'form-control' %>
  </p>
  
  <p>
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </p>
  
 
	<% end %>

  </div>
 
</div>
 