config/routes.rb
Rails.application.routes.draw do
  
  

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'trips/index'

	
	
  resources :trips do
  	resources :microposts
  end
  
	
  
  resources :guest
  
	resources :commitment
	
  	root 'static_pages#home'
  	get 'login'  => 'sessions#new'
	post 'login'  => 'sessions#create'
	delete 'logout'  => 'sessions#destroy'
	
	post '/trips/:id/users/new' => 'trips#add_user', as: :add_user
	delete 'trips/:id/users/:user_id' => 'trips#remove_user', as: :remove_user
	post '/users/:id/trips/new' => 'users#add_trip', as: :add_trip
	delete '/users/:id/trips/:trip_id' => 'users#remove_trip', as: :remove_trip
	
	resources :filters
	resources :users
	resources :password_resets, only:[:new, :create, :edit, :update]
	
 
	
  

end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor 	:remember_token, :activation_token, :reset_token
	before_save		:downcase_email
	
	has_many :users_trips, dependent: :destroy
	has_many :trips, through: :users_trips
	
	has_secure_password
	validates :name, presence: true, length: {maximum: 20}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 }, 
		format: {with: VALID_EMAIL_REGEX},
		uniqueness: true
	validates :password, length: {minimum:3}
	
	def User.digest(string)
		cost = BCrypt::Engine::MIN_COST	
		BCrypt::Password.create(string, cost: cost)
	end
	
	
	def User.new_token #class method
		SecureRandom.urlsafe_base64
	end
	
	def remember
		self.remember_token = User.new_token #generate token
		update_attribute(:remember_digest, User.digest(remember_token)) #encrypt & save
	end
	
	def authenticated?(remember_token)
		return false if remember_digest.nil?
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end
	
	def forget
		update_attribute(:remember_digest, nil)
	end
	
	def create_reset_digest
		self.reset_token = User.new_token
		update_attribute(:reset_digest, User.digest(reset_token))
		update_attribute(:reset_sent_at, Time.zone.now)
	end
	
	def send_password_reset_email
		UserMailer.password_reset(self).deliver_now
	end
	
	
	private
	
	def downcase_email
		self.email = email.downcase
	end
	
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  	before_action :correct_user,   only: [:edit, :update]
	
		
	def new
		@user = User.new
	end
	
	def show
		@user = User.find(params[:id])
		@trips = Trip.all
	end
	
	def create
  		@user = User.new(user_params)
  		if @user.save
  			log_in @user
 	   		flash[:success] = "Welcome to the Sample App!"
 	   		redirect_to @user
  		else
    		render 'new'
  		end
	end
	
	
	def index
		@users = User.all
		if params[:search]
    	  	flash.now[:success] = "Filtered List"
    	   	@users = User.where('name LIKE ?', "%#{params[:search]}%")
    	else
    	  	@users = User.all
    	end
    end
	
	def add_trip
		user = User.find(params[:id])
		trip = Trip.find(params[:user_id])
		user.trips << trip
		redirect_to user_path(user)
	end
	
	def remove_trip
		user = User.find(params[:id])
		trip = Trip.find(params[:trip_id])
		user.trips.delete(trip)
		redirect_to user_path(user)
	end
	
	private
  	def user_params
    	params.require(:user).permit(:name, :email, :password, :password_confirmation)
  	end
  	
  	def logged_in_user
  		unless logged_in?
  			flash[:danger]= "Please log in."
  			redirect_to login_path
  		end
  	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
 
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
 
    <%= f.label :email %><br>
    <%= f.text_field :email, class: 'form-control' %>
  
    <%= f.label :password %><br>
    <%= f.password_field :password, class: 'form-control' %>
  
    <%= f.label :passsword_confirmation%><br>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
 	<br>
    <%= f.submit "Create my account", class: "btn-srch	" %>
 
<% end %>

app/views/users/index.html.erb
<h1>All users</h1>

<br></br>

<div class="main">
<%= form_tag users_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search" %>
  </p>
<% end %>


<table>
<% @users.each do |user| %>
    <tr>
      	<td><%= user.name %></td>
		<td><%= user.email %></td> 
	</tr>
  <% end %>
</table>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<div class="row">
<div class="col-md-4 col-md-offset-3">
<%= render 'form' %>

<p>Already a user? <%= link_to 'Login', '#' %>
</div>


<br>
<%= check_box_tag(:plan) %>
<%= label_tag(:plan, "Prefer a schedule") %>
<%= check_box_tag(:discover) %>
<%= label_tag(:discover, "Carpe Diem") %>
<br></br>
<%= check_box_tag(:smoker) %>
<%= label_tag(:smoker, "I smoke") %>
<%= check_box_tag(:no_smoke) %>
<%= label_tag(:no_smoke, "No smoking!") %>
<br></br>
<%= check_box_tag(:drink_no) %>
<%= label_tag(:drink_no, "No drinking") %>
<%= check_box_tag(:drink_light) %>
<%= label_tag(:drink_light, "Light Drinker") %>
<%= check_box_tag(:drink_heavy) %>
<%= label_tag(:drink_heavy, "Heavy Drinker") %>
<br></br>
<%= check_box_tag(:early_bird) %>
<%= label_tag(:early_bird, "Early Bird") %>
<%= check_box_tag(:night_owl) %>
<%= label_tag(:night_owl, "Night Owl") %>
<br></br>
<%= check_box_tag(:coed) %>
<%= label_tag(:coed, "Only Coed") %>
<%= check_box_tag(:rainbow) %>
<%= label_tag(:rainbow, "LGTV") %>
<br></br>
<%= check_box_tag(:drive) %>
<%= label_tag(:drive, "I drive") %>


</div>

app/views/users/show.html.erb
<h1>USER PROFILE</h1>


<h3>Name: <%= @user.name %></h3>
<h3>Email: <%= @user.email %></h3>

<div>
  <h3>Upcoming Trips:</h3>


<div>
<% @user.trips.each do |trip| %>
    <div class="trip">
      	<%= image_tag trip.image %>
      	<h4><%= trip.name %></h4>
      	<p><%= trip.dest %></p>
      	<p><%= trip.month %></p>
		<p><%= trip.desc %></p>
		<p><%= trip.all_tags %></p>
		<p>
      	<%= link_to "#{trip.name}", trip_path(trip) %>
      	<%= button_to "Depart", remove_trip_path(@user, trip), :method => :delete %>
    	</p>
    </div>
</div>
    
    <% end %>
      
</div>