config/routes.rb
Rails.application.routes.draw do
  
  

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'trips/index'

	
	
  resources :trips do
  	resources :microposts
  end
  
	
  
  resources :guest
  
	resources :commitment
	
  	root 'static_pages#home'
  	get 'login'  => 'sessions#new'
	post 'login'  => 'sessions#create'
	delete 'logout'  => 'sessions#destroy'
	
	post '/trips/:id/users/new' => 'trips#add_user', as: :add_user
	delete 'trips/:id/users/:user_id' => 'trips#remove_user', as: :remove_user
	post '/users/:id/trips/new' => 'users#add_trip', as: :add_trip
	delete '/users/:id/trips/:trip_id' => 'users#remove_trip', as: :remove_trip
	
	resources :filters
	resources :users
	resources :password_resets, only:[:new, :create, :edit, :update]
	
 
	
  

end

app/models/filter.rb
class Filter < ActiveRecord::Base
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :trip
  default_scope -> { order(created_at: :desc) }
  validates :content, presence: true, length: { maximum: 140 }
  
  
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :trips, through: :taggings

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :trip
  
  
  
end

app/models/trip.rb
class Trip < ActiveRecord::Base
	has_many :users_trips, dependent: :destroy
	has_many :users, through: :users_trips
	has_many :taggings
	has_many :tags, through: :taggings
	has_many :microposts, dependent: :destroy
	
	def all_tags=(names)
	  self.tags = names.split(",").map do |name|
		  Tag.where(name: name.downcase.strip).first_or_create!
	  end
	end
 
	def all_tags
	  self.tags.map(&:name).join(", ")
	end

end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor 	:remember_token, :activation_token, :reset_token
	before_save		:downcase_email
	
	has_many :users_trips, dependent: :destroy
	has_many :trips, through: :users_trips
	
	has_secure_password
	validates :name, presence: true, length: {maximum: 20}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 }, 
		format: {with: VALID_EMAIL_REGEX},
		uniqueness: true
	validates :password, length: {minimum:3}
	
	def User.digest(string)
		cost = BCrypt::Engine::MIN_COST	
		BCrypt::Password.create(string, cost: cost)
	end
	
	
	def User.new_token #class method
		SecureRandom.urlsafe_base64
	end
	
	def remember
		self.remember_token = User.new_token #generate token
		update_attribute(:remember_digest, User.digest(remember_token)) #encrypt & save
	end
	
	def authenticated?(remember_token)
		return false if remember_digest.nil?
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end
	
	def forget
		update_attribute(:remember_digest, nil)
	end
	
	def create_reset_digest
		self.reset_token = User.new_token
		update_attribute(:reset_digest, User.digest(reset_token))
		update_attribute(:reset_sent_at, Time.zone.now)
	end
	
	def send_password_reset_email
		UserMailer.password_reset(self).deliver_now
	end
	
	
	private
	
	def downcase_email
		self.email = email.downcase
	end
	
	
end

app/models/users_trip.rb
class UsersTrip < ActiveRecord::Base
  belongs_to :user
  belongs_to :trip
end

app/controllers/filters_controller.rb
class FiltersController < ApplicationController
	def new
	end
	
	def index
		if params[:search]
    	  	flash.now[:success] = params[:search]
			@tags=Tag.find_by_name(params[:search])
			@trips = @tags.trips
	   	else
    	  	@trips=Trip.all	
    	end
  	end

end

app/controllers/tlinks_controller.rb
class TlinksController < ApplicationController
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :logged_in_user, only: [:create, :edit, :update, :destroy, :add_user]
  before_action :admin_user,     only: :destroy

  def index
  		@trips=Trip.all
  	end
  
  	def new
  		@trip=Trip.new
  	end
  
	def create
  		@trip = Trip.new(trip_params)	
  		@trip.lead=current_user.id
  		@trip.dest.split(",").each do |t|
  			@tags = @trip.tags.build(name: t.downcase.strip)
 		end 	
  		if @trip.save
      		flash[:success] = "Bom Voyage"
 			redirect_to @trip
  		else
    		render 'new'
  		end	
	end
	
	def show
		@trip = Trip.find(params[:id])
		@users = User.all
		@microposts = @trip.microposts
	end
	
	
	def edit
		@trip = Trip.find(params[:id])
	end
	
	def update
  		@trip = Trip.find(params[:id])
  		if @trip.update(trip_params)
  			flash[:success] = "Trip Profile updated"
    		redirect_to @trip
  		else
    		render 'edit'
  		end
  
	end
	
	def destroy
		Trip.find(params[:id]).destroy
		flash[:success]="Trip deleted"
		redirect_to trips_path
	end
	

	def add_user
  	 	trip = Trip.find(params[:id])
  	 	user = current_user
  	#OJO:or User.find(params[:user_id]) / wouldnt need @user=Users.all
  	 	trip.users << user
  	 	redirect_to trip_path(trip)
	end
	
	def remove_user
  	 	trip = Trip.find(params[:id])
  	 	user = User.find(params[:user_id])
  	 	trip.users.delete(user)
  	 	redirect_to trip_path(trip)
	end

	def logged_in_user
  		unless logged_in?
  			flash[:danger]= "Please log in."
  			redirect_to login_path
  		end
  	end


	private
  	def trip_params
    	params.require(:trip).permit(:name, :dest, :desc, :month, :image, :lead, :all_tags)
  	end	
  	
  	
  	
  	def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
	
	

	
  	

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  	before_action :correct_user,   only: [:edit, :update]
	
		
	def new
		@user = User.new
	end
	
	def show
		@user = User.find(params[:id])
		@trips = Trip.all
	end
	
	def create
  		@user = User.new(user_params)
  		if @user.save
  			log_in @user
 	   		flash[:success] = "Welcome to the Sample App!"
 	   		redirect_to @user
  		else
    		render 'new'
  		end
	end
	
	
	def index
		@users = User.all
		if params[:search]
    	  	flash.now[:success] = "Filtered List"
    	   	@users = User.where('name LIKE ?', "%#{params[:search]}%")
    	else
    	  	@users = User.all
    	end
    end
	
	def add_trip
		user = User.find(params[:id])
		trip = Trip.find(params[:user_id])
		user.trips << trip
		redirect_to user_path(user)
	end
	
	def remove_trip
		user = User.find(params[:id])
		trip = Trip.find(params[:trip_id])
		user.trips.delete(trip)
		redirect_to user_path(user)
	end
	
	private
  	def user_params
    	params.require(:user).permit(:name, :email, :password, :password_confirmation)
  	end
  	
  	def logged_in_user
  		unless logged_in?
  			flash[:danger]= "Please log in."
  			redirect_to login_path
  		end
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title = " ")
		base_title = "Travel"
		if page_title.empty?
			base_title
		else 
			"#{page_title} | #{base_title}"
		end
	end

end

app/helpers/filters_helper.rb
module FiltersHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def remember(user)
		user.remember
		cookies.permanent.signed[:user_id] = user.id
		cookies.permanent[:remember_token] = user.remember_token
	end
	
	def log_in(user)
		session[:user_id] = user.id
	end
	
	def current_user
		if (user_id = session[:user_id])
			@current_user ||= User.find_by(id: session[:user_id])
		elsif (user_id = cookies.signed[:user_id])
			user= User.find_by(id: user_id)
			if user && user.authenticated?(cookies[:remember_token])
				log_in user
				@current_user = user
			end
		end
	end
	
	def forget(user)
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end
	
	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end
	
	def logged_in?
		!current_user.nil?
	end
	
	def current_user?(user)
		user == current_user
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

end

app/helpers/tlinks_helper.rb
module TlinksHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar-custom">
	<div class="container">
		<%= link_to "NEWCO", root_path, id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "Explore Existing Trips", trips_path %></li>
				<li><%= link_to "Start a Trip", new_trip_path %></li>
				
				<% if logged_in? %>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown"  >
							Account <b class="caret"></b>
						</a>	
						<ul class="dropdown-menu">
							<li><%= link_to "Profile", current_user %></li>
							<li><%= link_to "Settings", '#' %></li>
							<li class="divider"></li>
							<li>
								<%= link_to "Logout", logout_path, method:"delete" %>
							</li>
						</ul>
					</li>
				<% else %>
					<li><%= link_to "Login", login_path %></li>
				<% end %>
			</ul>
		</nav>
	</div>
	
	
		
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  
  	<title><%= full_title(yield(:title)) %></title>
  
  	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  	<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
	<script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  	<%= csrf_meta_tags %>
  	<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
	<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
	<meta content="SlKTCvDr5MFLP0EkthJHQeGIw+Yp0oGUrxvAeQMnVts=" name="csrf-token" />
	
</head>
	<script>
	var map;
	function initialize() {
	  var mapOptions = {
		zoom: 8,
		center: new google.maps.LatLng(-34.397, 150.644),
		mapTypeId: google.maps.MapTypeId.ROADMAP
	  };
	  map = new google.maps.Map(document.getElementById("map-canvas"),
		  mapOptions);
	}
	
	

	$(document).ready(function(){
		initialize();
	});
    </script>
<body>

	<%= render 'layouts/header' %>
	
	
	<br></br>
	<% flash.each do |message_type, message| %>
		<div class="alert alert-<%= message_type %>"><%= message %></div>
	<% end %>
	<%= yield %>
	<%= debug(params) if Rails.env.development? %>
</body>
</html>